name: Website Deploy

on:
  push:
    branches:
      - main   # Trigger on push to main

jobs:
  # -------------------------------
  # 1. Build & Push Docker Image
  # -------------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: |
          docker build -t shinjan7/github_nextjs:latest .

      - name: Push Docker image
        run: |
          docker push shinjan7/github_nextjs:latest

  # -------------------------------
  # 2. Deploy to AWS EC2
  # -------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build   # deploy only after build succeeds

    steps:
      - name: Deploy to EC2
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USER }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            docker pull shinjan7/github_nextjs:latest
            docker stop nextjs-container || true
            docker rm nextjs-container || true
            docker run -d --name nextjs-container -p 3000:3000 shinjan7/github_nextjs:latest
