name: Website Build and Deploy

on:
  push:
    branches:
      - main

jobs:
  # -------------------------------
  # 1. Build & Push Docker Image
  # -------------------------------
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build Docker image
        run: docker build -t shinjan7/github_nextjs:latest .

      - name: Push Docker image
        run: docker push shinjan7/github_nextjs:latest

  # -------------------------------
  # 2. Deploy to Fly.io
  # -------------------------------
  deploy:
    runs-on: ubuntu-latest
    needs: build

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Install Fly CLI
        run: curl -L https://fly.io/install.sh | sh

      - name: Set Fly CLI path
        run: echo "$HOME/.fly/bin" >> $GITHUB_PATH

      - name: Deploy to Fly.io
        run: flyctl deploy --remote-only
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
